### ISSUE TITLE
incorrect spe test file dimension

### ISSUE THREAD

**Issue by sangttruong** [r-hyperspec/hySpc.read.spe#1]
The blut1.spe file doesn't work because its ydim = 0, and ydim is used to set the dimention of another matrix (hence the function throws an error). read_spe() works just fine on spe_format_3.0.spe.

**Comment by GegznaV** [comment]
It seems the file is read as expected (without errors or warnings):

``` r
suppressPackageStartupMessages({
  library(hySpc.read.spe)
})

blut1 <- system.file("extdata", "blut1.SPE", package = "hySpc.read.spe")
spc_blut1 <- read_spe(blut1)
spc_blut1
#> hyperSpec object
#>    10 spectra
#>    9 data columns
#>    1023 data points / spectrum
```

<sup>Created on 2021-07-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>


Do I miss something here, @sangttruong. Can you provide a reprex, please, and/or describe how to reproduce the issue?

**Comment by GegznaV** [comment]
Has this already been fixed, @sangttruong, @cbeleites?

**Comment by cbeleites** [comment]
(I haven't done anything so far)
