### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by cbeleites** [r-hyperspec/hySpc.read.spe#11]
with some file in `inst/extdata/`, provide examples for

- `read_spe()`
- `spe_showcalpoints()`

**Comment by sangttruong** [comment]
This issue has been resolved with pull request of merging branch Fix/010 vignette

**Comment by cbeleites** [comment]
@sangttruong: FYI it's best to include a full linkt to the PR that closes this issue, e.g. https://github.com/r-hyperspec/hySpc.read.spe/pull/15
