### ISSUE TITLE
Is it reasonable to rename `xaxis` to `wl_units` or similar?

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.spe#20]
Is it reasonable to rename argument `xaxis` to `xaxis_units`,  **`wl_units`**  or similar?

@cbeleites, what do you think?

***

**UPDATE**

Tasks:

- [x] Rename arg to `wl_units`.
- [x] Deprecate `xaxis` for backward compatibility.
- [x] Update `NEWS.md`.

**Comment by bryanhanson** [comment]
I think renaming would be good -- a lot clearer.  `wl_units` seems pretty consistent with other names we have in various places.
