### ISSUE TITLE
Unused files in `inst/extdata` dir

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.spe#25]
There are many (small) files in `inst/extdata` directory, that are not used. As they are small, they may be left in the package. What do you think @cbeleites, @sangttruong, @bryanhanson? Are there any plans to use them in e.g., vignettes, unit tests, or examples?

The PDF manual is build-ignored.

**Comment by bryanhanson** [comment]
I will defer to CB, but in general if we are not using files in any way, I'd say they should be deleted, as a principle.

If we leave the manual and it is not `.gitignore`'d we may be breaking someone's copyright by distributing it.  Haven't looked closer, just a general comment.

**Comment by cbeleites** [comment]
- [ ] delete `readspe.h` (belongs to Princeton Instruments, should never have been in our repos)
- [ ] delete `winspec.pdf`  (belongs to Princeton Instruments, should never have been in our repos)
- [ ] `manuals.txt` points the interested reader to that documentation by Princeton Instruments  
      it can stay, but the info would IMHO be better in the documentation of `read_spe()`.
- [ ] `*.spc` should not be in this repo. I don't think they add anything new to **hySpc.read.spc** -> delete them.
