### ISSUE TITLE
Vignette: add more text/code to vignette or delete it completely

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.spe#27]
More text and code should be added to the vignette otherwise it should be deleted completely.
 
 Would it be sufficient to add everything to examples? Please, express your point of view and opinion on this @sangttruong, @cbeleites, @bryanhanson

**Comment by bryanhanson** [comment]
I defer to CB, but from my perspective it looks similar to `jdx` in that the examples should be sufficient, and no vignette is desirable, since it wouldn't add anything compared to the examples and would be extra maintenance should the examples change.

**Comment by GegznaV** [comment]
I also vote for examples only and removed vignettes.

**Comment by cbeleites** [comment]
I agree, let's delete the vignette.

**Comment by sangttruong** [comment]
I agree.
