### ISSUE TITLE
Read documentation and identify issues

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.spe#28]
@sangttruong, please read the documentation of this package (https://r-hyperspec.github.io/hySpc.read.spe/) and tell whether, in your opinion, it is of sufficient quality or not. Please, suggest bellow, how should it be improved. If possible, add improvements as a separate PR. If it is OK, let us know too.

**Comment by sangttruong** [comment]
I think the documentation of spe is good now.
