### ISSUE TITLE
Who should be authors, maintainers, and contributors(aut, cre, ctb) of this package (hySpc.read.spe)?

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.spe#4]
It gets a bit confusing, as it is not always clear who should be included as authors, maintainers, and contributors (`aut`, `cre`, `ctb`) of this package (**`hySpc.read.spe`**) and other packages that are made of code separated from the **`hyperSpec`**, I open this issue for discussion and clarifications.

In my opinion, @cbeleites knows best, who created what in **`hyperSpec`**.

@cbeleites, when you have time, please, review the `DESCRIPTION` file and let us know if the author list is complete.

**Comment by bryanhanson** [comment]
Closed via https://github.com/r-hyperspec/hySpc.read.spe/commit/02b641940796ef48eba065f042273cf68be7dc7c
