### ISSUE TITLE
Author list

### ISSUE THREAD

**Issue by GegznaV** [r-hyperspec/hySpc.read.spe#40]
Check and update the author and contributor list on DESCRIPTION.

**Comment by bryanhanson** [comment]
I don't think I should be on the author list for this one, as I have not contributed any code that I can remember.

**Comment by GegznaV** [comment]
@bryanhanson, you are listed as a contributor, not as an author.

>    person("Bryan",     "Hanson",   role = c("ctb"))

**Comment by GegznaV** [comment]
This is the GitHub report on contributors for this repo (you are listed there):

![image](https://user-images.githubusercontent.com/12725868/129229948-12413969-87d9-45ab-bb5a-67e8db95c58a.png)

**Comment by bryanhanson** [comment]
I guess I don't know what our standards are for being included as `ctb` but looking at my commits they mostly are either trivial or result from merges submitted by others.  There are some related to managing the entire set of repos too.  So I'm OK to be included, or not.

**Comment by GegznaV** [comment]
This (and last) summer you actively participated in solving various issues, opened issues for Sang and others to solve. So non-code contributions of yours count as well.
